### ISSUE TITLE
Error thrown while loading add-on

### ISSUE THREAD

**Issue by cary-rowen** [mltony/nvda-task-switcher#1] opened 2024-05-18 04:11 UTC
```log
ERROR - globalPluginHandler.initialize (12:08:26.665) - MainThread (6736):
Error initializing global plugin <class 'globalPlugins.taskSwitcher.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 32, in initialize
  File "C:\Users\cary\AppData\Roaming\nvda\addons\taskSwitcher\globalPlugins\taskSwitcher.py", line 846, in __init__
    initHwndObserver()
  File "C:\Users\cary\AppData\Roaming\nvda\addons\taskSwitcher\globalPlugins\taskSwitcher.py", line 314, in initHwndObserver
    queryObserver("init", cacheFileName=cacheFileName, bootupTime=bootupTime)
  File "C:\Users\cary\AppData\Roaming\nvda\addons\taskSwitcher\globalPlugins\taskSwitcher.py", line 270, in queryObserver
    result = observerDll.queryHwnds(json.dumps(request).encode('utf-8'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError -529697949] Windows Error 0xe06d7363
```

**Comment by mltony** [comment] 2024-05-18 18:32
Could you check a few things for me:
1. Make sure that `%TMP%` is defined on your computer and points to a directory where files can be created and written.
2. Try manually launching files:
    `globalPlugins\x64\cbt_client.exe`
    and 
    `globalPlugins\win32\cbt_client.exe`

This error indicates something broke in C++ layer, which is unfortunate. I just tested on a clean windows installation and it works fine for me. If these steps above don't work, I'll try to add some debugging statements to nail down which line causes the problem.

**Comment by cary-rowen** [comment] 2024-05-19 01:17
Hi @mltony 
I can make sure %tmp% exists and is writable.

I manually executed the executable file you mentioned and did not observe any different behavior.

When I execute the file you mentioned on the command line it outputs "Cannot find target window"

**Comment by mltony** [comment] 2024-05-19 02:58
I managed to reproduce this and fixed the bug. Try:
https://github.com/mltony/nvda-task-switcher/releases/download/v0.2/taskSwitcher-0.2.nvda-addon
But you need to manually delete cache file since v0.1 didn't fill out boottime field correctly. I'll close this but feel free to reopen if this still doesn't work for you.

**Closed as completed by mltony** 2024-05-19 02:58 UTC

**Comment by cary-rowen** [comment] 2024-05-19 10:05
Hi @mltony 

Another error occurred:
```log
ERROR - globalPluginHandler.initialize (17:59:43.329) - MainThread (9764):
Error initializing global plugin <class 'globalPlugins.taskSwitcher.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 32, in initialize
  File "C:\Users\cary\AppData\Roaming\nvda\addons\taskSwitcher\globalPlugins\taskSwitcher.py", line 846, in __init__
    initHwndObserver()
  File "C:\Users\cary\AppData\Roaming\nvda\addons\taskSwitcher\globalPlugins\taskSwitcher.py", line 314, in initHwndObserver
    queryObserver("init", cacheFileName=cacheFileName, bootupTime=bootupTime)
  File "C:\Users\cary\AppData\Roaming\nvda\addons\taskSwitcher\globalPlugins\taskSwitcher.py", line 277, in queryObserver
    raise RuntimeError(f"HWNDObserver error: {error}")
RuntimeError: HWNDObserver error: Failed to load cache from file: Invalid boot time read from cache on disk: 
```

**Comment by mltony** [comment] 2024-05-19 17:15
Delete your cache file `%TMP%\NVDATaskSwitcherObserverCache.json` and try again.
